# Generated by Django 4.0.4 on 2022-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
