# Generated by Django 4.0.4 on 2022-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commnent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commnent',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='commnent',
            name='post_id',
        ),
    ]
